# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: algorithm_stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'algorithm_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61lgorithm_stream.proto\x12\theuristic\"=\n\x13\x41lgorithmRunRequest\x12\x0c\n\x04\x61lgo\x18\x01 \x01(\t\x12\x0b\n\x03src\x18\x02 \x01(\t\x12\x0b\n\x03\x64st\x18\x03 \x01(\t\";\n\x11\x41lgorithmRunStart\x12\x0c\n\x04\x61lgo\x18\x01 \x01(\t\x12\x0b\n\x03src\x18\x02 \x01(\t\x12\x0b\n\x03\x64st\x18\x03 \x01(\t\"\xb2\x01\n\rAlgorithmStep\x12\x0c\n\x04\x61lgo\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x0c\n\x04node\x18\x04 \x01(\t\x12\x11\n\tfrom_node\x18\x05 \x01(\t\x12\x0f\n\x07to_node\x18\x06 \x01(\t\x12\x11\n\topen_size\x18\x07 \x01(\x05\x12\t\n\x01g\x18\x08 \x01(\x01\x12\t\n\x01\x66\x18\t \x01(\x01\x12\x0c\n\x04\x64ist\x18\n \x01(\x01\x12\x0c\n\x04path\x18\x0b \x03(\t\"\xc1\x01\n\x0bRouteResult\x12\x0c\n\x04path\x18\x01 \x03(\t\x12\x14\n\x0ctotal_weight\x18\x02 \x01(\x01\x12\x16\n\x0etotal_delay_ms\x18\x03 \x01(\x01\x12\x17\n\x0ftotal_jitter_ms\x18\x04 \x01(\x01\x12\x15\n\ravg_loss_rate\x18\x05 \x01(\x01\x12\x1a\n\x12min_bandwidth_mbps\x18\x06 \x01(\x01\x12\x11\n\thop_count\x18\x07 \x01(\x05\x12\x17\n\x0fstability_score\x18\x08 \x01(\x01\"c\n\x11\x41lgorithmComplete\x12\x0c\n\x04\x61lgo\x18\x01 \x01(\t\x12\x0b\n\x03src\x18\x02 \x01(\t\x12\x0b\n\x03\x64st\x18\x03 \x01(\t\x12&\n\x06result\x18\x04 \x01(\x0b\x32\x16.heuristic.RouteResult\"\xae\x01\n\x14\x41lgorithmStreamEvent\x12\x31\n\trun_start\x18\x01 \x01(\x0b\x32\x1c.heuristic.AlgorithmRunStartH\x00\x12(\n\x04step\x18\x02 \x01(\x0b\x32\x18.heuristic.AlgorithmStepH\x00\x12\x30\n\x08\x63omplete\x18\x03 \x01(\x0b\x32\x1c.heuristic.AlgorithmCompleteH\x00\x42\x07\n\x05\x65vent2k\n\x16\x41lgorithmStreamService\x12Q\n\x0cRunAlgorithm\x12\x1e.heuristic.AlgorithmRunRequest\x1a\x1f.heuristic.AlgorithmStreamEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'algorithm_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALGORITHMRUNREQUEST']._serialized_start=37
  _globals['_ALGORITHMRUNREQUEST']._serialized_end=98
  _globals['_ALGORITHMRUNSTART']._serialized_start=100
  _globals['_ALGORITHMRUNSTART']._serialized_end=159
  _globals['_ALGORITHMSTEP']._serialized_start=162
  _globals['_ALGORITHMSTEP']._serialized_end=340
  _globals['_ROUTERESULT']._serialized_start=343
  _globals['_ROUTERESULT']._serialized_end=536
  _globals['_ALGORITHMCOMPLETE']._serialized_start=538
  _globals['_ALGORITHMCOMPLETE']._serialized_end=637
  _globals['_ALGORITHMSTREAMEVENT']._serialized_start=640
  _globals['_ALGORITHMSTREAMEVENT']._serialized_end=814
  _globals['_ALGORITHMSTREAMSERVICE']._serialized_start=816
  _globals['_ALGORITHMSTREAMSERVICE']._serialized_end=923
# @@protoc_insertion_point(module_scope)
