# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: heuristic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'heuristic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fheuristic.proto\x12\theuristic\"]\n\nNodeMetric\x12\x10\n\x08\x63pu_load\x18\x01 \x01(\x01\x12\x11\n\tjitter_ms\x18\x02 \x01(\x01\x12\x11\n\tqueue_len\x18\x03 \x01(\x05\x12\x17\n\x0fthroughput_mbps\x18\x04 \x01(\x01\"X\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12&\n\x07metrics\x18\x04 \x01(\x0b\x32\x15.heuristic.NodeMetric\"\\\n\nLinkMetric\x12\x10\n\x08\x64\x65lay_ms\x18\x01 \x01(\x01\x12\x11\n\tjitter_ms\x18\x02 \x01(\x01\x12\x11\n\tloss_rate\x18\x03 \x01(\x01\x12\x16\n\x0e\x62\x61ndwidth_mbps\x18\x04 \x01(\x01\"[\n\x04Link\x12\x0b\n\x03src\x18\x01 \x01(\t\x12\x0b\n\x03\x64st\x18\x02 \x01(\t\x12\x11\n\tavailable\x18\x03 \x01(\x08\x12&\n\x07metrics\x18\x04 \x01(\x0b\x32\x15.heuristic.LinkMetric\"b\n\rGraphSnapshot\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x1e\n\x05nodes\x18\x02 \x03(\x0b\x32\x0f.heuristic.Node\x12\x1e\n\x05links\x18\x03 \x03(\x0b\x32\x0f.heuristic.Link\"2\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2V\n\x10HeuristicService\x12\x42\n\x0bUpdateGraph\x12\x18.heuristic.GraphSnapshot\x1a\x19.heuristic.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heuristic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODEMETRIC']._serialized_start=30
  _globals['_NODEMETRIC']._serialized_end=123
  _globals['_NODE']._serialized_start=125
  _globals['_NODE']._serialized_end=213
  _globals['_LINKMETRIC']._serialized_start=215
  _globals['_LINKMETRIC']._serialized_end=307
  _globals['_LINK']._serialized_start=309
  _globals['_LINK']._serialized_end=400
  _globals['_GRAPHSNAPSHOT']._serialized_start=402
  _globals['_GRAPHSNAPSHOT']._serialized_end=500
  _globals['_UPDATERESPONSE']._serialized_start=502
  _globals['_UPDATERESPONSE']._serialized_end=552
  _globals['_HEURISTICSERVICE']._serialized_start=554
  _globals['_HEURISTICSERVICE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
