# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import heuristic_pb2 as heuristic__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in heuristic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HeuristicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateGraph = channel.unary_unary(
                '/heuristic.HeuristicService/UpdateGraph',
                request_serializer=heuristic__pb2.GraphSnapshot.SerializeToString,
                response_deserializer=heuristic__pb2.UpdateResponse.FromString,
                _registered_method=True)


class HeuristicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeuristicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGraph,
                    request_deserializer=heuristic__pb2.GraphSnapshot.FromString,
                    response_serializer=heuristic__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'heuristic.HeuristicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('heuristic.HeuristicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HeuristicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heuristic.HeuristicService/UpdateGraph',
            heuristic__pb2.GraphSnapshot.SerializeToString,
            heuristic__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
